### ISSUE TITLE
Casos confirmados caen de 6.9m a 2.8m a partir de 2022-08-18

### ISSUE THREAD

**Issue by panchosoft** [carranco-sga/Mexico-COVID-19#1]
Hola, gracias por el gran trabajo que se realiza en este repositorio a través de los días y ya años.

Noté que en el archivo Mexico_COVID19_CTD.csv, a partir del 2022-08-18 los casos confirmados acumulados caen de 6.9 millones a 2.8 millones. Aquí hay una visualización del contenido del archivo en formato JSON:

![image](https://user-images.githubusercontent.com/415730/189512252-d555fa08-c6f1-4d41-a402-243d4a730c37.png)

Podría ser un problema que venga desde la fuente original de la información?

Saludos!

**Comment by carranco-sga** [comment]
Saludos.

Una disculpa por la demora. El repositorio ahora está completamente automatizado.
Parece ser que es porque las bases de datos abiertas que publica ahora la SSa sólo tienen casos de enero del 2022 a la fecha.
