### ISSUE TITLE
Find the sifted data of suspect cases per state after February 29.

### ISSUE THREAD

**Issue by carranco-sga** [carranco-sga/Mexico-COVID-19#1]
Parece ser que las tablas de información por estado de los casos sospechosos fueron eliminadas del sitio gob.mx un par de días después de que cada una fue subida. Las tablas disponibles en el repositorio son las que he podido archivar.

Nos faltan los datos desde el 29 de febrero al 13 de marzo. Sería útil tenerlos para analizar el número de casos analizados en laboratorio en los primeros días del brote en el país.

It seems the tables of information per state of the suspected cases were taken offline a couple of days after each one was uploaded. The tables in the repo are the tables I managed to download from the gob.mx site.

We're missing the data from February 29 through March 13. This would be useful to track the extent of testing done in the first days of the outbreak.

**Comment by kinduff** [comment]
@carranco-sga ¿tienes el enlace en donde podrían haber estado? quizás puedo encontrar algo de información archivada

**Comment by carranco-sga** [comment]
@kinduff Gracias por la oferta, pero por desgracia no parece haber ningún archivo de los enlaces siquiera, ya que los documentos adjuntos del sitio gob.mx parecen seguir un orden secuencial. 
Me parece que Luis G. Canales intentó usar el historial de Google sin mucho éxito. 
De cualquier forma, los datos de la epidemia temprana parece que los están reportando junto con los datos nuevos en los datos abiertos que publican.

**Comment by carranco-sga** [comment]
La existencia de las bases de datos abiertos parece subsanar la falta de las tablas de casos de días anteriores, por lo que este issue ya no es relevante.
