### ISSUE TITLE
Uso de repo en covidMex

### ISSUE THREAD

**Issue by pablorm296** [carranco-sga/Mexico-COVID-19#10]
Estimado Gabriel,

Tu repositorio es uno de los más completos que he visto en el trabajo de recolección y limpieza de datos sobre el brote de SARS-CoV-2 en México. Programé y mantengo [un paquete en R que concentra distintas fuentes de datos](https://github.com/pablorm296/covidMex/) para su fácil acceso y análisis. ¿Podría incluir tu repositorio y tus datos en el paquete?

Muchas gracias por tu trabajo. ¡Saludos!

**Comment by carranco-sga** [comment]
Muchas gracias por sus comentarios. ¡Adelante, con gusto! Precisamente por eso he subido los datos.

Saludos,
Gabriel.
