### ISSUE TITLE
Posible discrepancia en casos negativos Base de Datos vs CDT

### ISSUE THREAD

**Issue by mariorz** [carranco-sga/Mexico-COVID-19#11]
Hola.
Me parece hay una discrepancia entre los casos negativos reportados en el CDT del 14 de Marzo y la DB publicada el mismo día por la DGE. Explico más aquí: https://github.com/mariorz/covid19-mx-time-series/wiki/Incidentes-encontrados-en-la-base-de-datos-DGE%E2%80%93COVID19

Saludos!

**Comment by carranco-sga** [comment]
¡Muchas gracias por el dato! En efecto, parece que se reportan más casos negativos en la base de datos que en los CTDs. Quizá se deba a una diferencia en la fecha de corte de los datos, pero esto es especulació sin más información.

Agrego un link a tu comentario en el repositorio.
Saludos, Gabriel

**Comment by carranco-sga** [comment]
Lo dejo abierto para que no se me pase hacer la aclaración.

**Comment by carranco-sga** [comment]
Finalmente, y de forma muy atrasada, hice la nota referenciando tu explicación. Por alguna razón se me olvidó por completo realizarla hasta que revisé los issues. Una disculpa.

Saludos,
Gabriel.
