### ISSUE TITLE
Data for "positivos" and "sospechosos" is not uploading

### ISSUE THREAD

**Issue by mansilla** [carranco-sga/Mexico-COVID-19#12]
@carranco-sga as the title suggests the data from positive cases and suspicious cases are not getting updated since April 18th. Nevertheless, the data for "deaths" is up to date. This is due to a bug in the uploading process perhaps?
Thanks in any case for your work.

**Comment by carranco-sga** [comment]
Greetings. The Health Secretariat hasn't published confirmed or suspect cases tables since April 19, as I comment [here](https://github.com/carranco-sga/Mexico-COVID-19/tree/master/CTD/Documents). This appears to be the result of Open data being published.

**Comment by mansilla** [comment]
Oh. I see. So the data in the folder: `/CTD/Scraped_data` should be considered "obsolete"? I mean, you won't be updating that anymore.

**Comment by carranco-sga** [comment]
I'll still be archiving the official data and transcribing the deaths by state table for as long as they publish them, however, this is more of an afterthought since this data is included, raw, in the open data they publish daily, and that I archive in the Open_data folder.
