### ISSUE TITLE
Problemas con el encoding en el archivo csv de datos abiertos

### ISSUE THREAD

**Issue by rodrigolece** [carranco-sga/Mexico-COVID-19#13]
Hola Gabriel,

No sé si te has dado cuenta, pero desde el día 24 de abril hay un error de encoding en los archivos csv de datos abiertos. Los archivos usan UTF-8 en principio, pero alguién copió y pegó "Estados Unidos de América" de un archivo que utilizaba ISO-8858-1 (latin-1). Desde ese día el archivo está corrompido porque en UTF-8 la "é" de latin-1 es un carácter inválido (probablemente lo que vas a ver es "Estados Unidos de Am�rica".

Este error se ha propagado y en particular los archivos zip que tú subes tienen el mismo problema.

En el [repositorio que yo mantengo](https://github.com/mexicovid19/Mexico-datos/) puse instrucciones sobre cómo arreglarlo. Me dio bastantes dolores de cabeza pero encontré un script de Perl que lo arregla y convierto todo a UTF-8 válido (también siéntete libre si quieres ahorrarte la molestia de convertir todos tus archivos, si quieres agarra los archivos csv directamente que se encuentran bajo el directorio `datos_abiertos/raw/`).

Dime si tienes cualquier duda. Instalar los el módulo de Perl me costó un poquito de trabajo, y me podrás decir si las instrucciones que escribí son lo suficientemente claras.

Por último, te podría pedir que como favor pusieras el link a nuestro repo? Y eso me importa menos pero tal vez también a [nuestro tablero](https://mexicovid19.github.io/Mexico/)?

Saludos,
Rodrigo

**Comment by carranco-sga** [comment]
Hola,

Muchas gracias por la observación. 
En efecto no me había dado cuenta de los problemas de encoding (en particular no me he fijado mucho en las columnas distintas de las numéricas que hasta el momento no tienen problemas de codificación.)
Con gusto enlazo su repositorio para quienes quieran las bases de datos bonitas que ustedes ofrecen, y agrego un enlace a su trabajo.

En cuanto haga las notas correspondientes menciono y cierro el issue.

Saludos,
Gabriel.

**Comment by carranco-sga** [comment]
Perdón por la demora en publicar el enlace a su trabajo. https://github.com/carranco-sga/Mexico-COVID-19/commit/304b67299ec819f1a1c07049d10c7d62463066d4 agrega varios enlaces a su repositorio y su tablero.

Asimismo, muchas gracias por la observación. He hecho las notas correspondientes (con el enlace a sus soluciones) a los problemas con la codificación en https://github.com/carranco-sga/Mexico-COVID-19/commit/480d571800bacc4f9e2940ba3acac8bea8fd6829.

Saludos,
Gabriel
