### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by owahltinez** [carranco-sga/Mexico-COVID-19#14]
Primero de todo, muchas gracias por el trabajo realizado en este repositorio! Puedes por favor incluir una licencia explicita para este repositorio? Sugiero mantener MIT, puesto que los datos parecen provenir de [este otro repositorio](https://github.com/mexicovid19/Mexico-datos).

**Comment by carranco-sga** [comment]
Gracias por su comentario. 
He estudiado el incluir una licencia explícita para los contenidos del repositorio, sin embargo, dado que los datos del gobierno federal tienen su propia licencia y existen contribuciones que no son mías, no entiendo lo suficiente como para asignar una licencia global al repositorio. Seguiré buscando la manera de poder establecer una licencia.

Estos datos no provienen del excelente trabajo de rodrigolece y cols., sino que son capturados y analizados [directamente](https://github.com/carranco-sga/Mexico-COVID-19/tree/master/Open_data) de la [fuente oficial](https://www.gob.mx/salud/documentos/datos-abiertos-152127).
Los scripts y demás métodos usados para construir los datos extraídos de los datos oficiales se encuentran en diferentes partes de este repositorio.

**Comment by owahltinez** [comment]
Entendido, gracias!
