### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [carranco-sga/Mexico-COVID-19#15]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/LWDW8F
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by carranco-sga** [comment]
Greetings, @reeshmabijosh.

I'd be glad to help maintain the appropriate information there to help make this repository more useful. How can I get started?

**Comment by reeshmabijosh** [comment]
Hello,

Thanks for your willingness to contribute.
 Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and
you will get the necessary permissions for editing your dataset.
Then please add relevant metadata - description and keywords to your
dataset.

Thanks
Reeshma K
