### ISSUE TITLE
Muchas gracias

### ISSUE THREAD

**Issue by deathwebo** [carranco-sga/Mexico-COVID-19#3]
Hola @carrango-sga he estado buscando por todos lados por esta información. Estoy tratando de desarrollar un mapa y página de consulta fácil para los usuarios. Estaba usando el raw data de serendipia pero no han actualizado más allá del 19 de marzo. He estado siguiendo los reportes técnicos pero no encontraba la información desglosada por estado.

Estoy usando python y pandas para parsear y alimentar las bases de datos para utilizarlas en un api que alimente el sitio.

Quería dar las gracias por hacer disponible en este formato los datos y espero continúe su trabajo.

¡Saludos!

**Comment by carranco-sga** [comment]
Le agradezco sus amables palabras. Espero que estos datos sean de ayuda a usted y al país. Seguiré actualizándolos (y manteniéndolos en el mismo formato) hasta dónde me sea posible.

Saludos,
Gabriel.
