### ISSUE TITLE
Recovered cases states "0" at 2020-03-24 in Mexico_COVID19.csv

### ISSUE THREAD

**Issue by jRicciL** [carranco-sga/Mexico-COVID-19#5]
Qué tal @carranco-sga 
Primero que nada agradecerte el esfuerzo que estás haciendo. Gracias a tu repositorio he podido hacer una aplicación web para el monitoreo de casos: https://joelricci.shinyapps.io/covid_mx_jrl/
Por otro lado he levantado este issue para preguntar sobre el valor de casos recuperados a la fecha del 24 de marzo del 2020. Dicho valor indica 0. ¿Esto se debe a que los reportes ya no están incluyendo dicho valor?

**Comment by carranco-sga** [comment]
Hola, @jRicciL. Gracias por tus amables comentarios. ¡Me alegra ver los datos visualizados! Agregaré una referencia al README del repositorio para quienes quieran ver las gráficas.

Respecto a tu pregunta, precisamente, el comunicado técnico diario ya no saca datos sobre pacientes recuperados. (Ni dan más información de los fallecidos que el estado). Antes lo que hice fue extrapolar lo que decían en los CTD y las conferencias sobre las características de los pacientes y modificar la tabla de casos diarios en csv a mano, identificando a los pacientes, para sacar la tabla resumen. Dado que ayer borraron la información de casos recuperados del CTD y hoy con otra defunción, no dieron específicos de la edad en la conferencia, he decidido que es mejor no reportar la situación específica de los pacientes como lo hice hasta ayer.

La SSa en sus conferencias diarias sí saca porcentajes de pacientes recuperados, pero no hay datos abiertos respecto a eso. (Y no he podido ponerme a vaciarlos a mano a partir de las conferencias). Al parecer el criterio que han mencionado para pacientes recuperados es 14 días después de la sintomatología, pero no he hecho los números para ver más o menos qué número de pacientes deberían de clasificarse como recuperados ahora. 

A lo mejor con las tablas de casos diarios puedo sacar una **conjetura** de casos sospechosos, pero necesito implementar el código. Veré si puedo hacer algo rápido en un par de horas.

Te agradeceré cualquier sugerencia. Saludos,
Gabriel.

**Comment by carranco-sga** [comment]
Tomé la fecha de inicio de síntomas de cada paciente listado por día y me fijé en la fecha del reporte diario. Si la diferencia entre la fecha del reporte y la del inicio de síntomas era igual o mayor a 14 días, lo consideré recuperado. Obtuve lo siguiente:

``` csv
Fechas,AGU_CR,BCN_CR,BCS_CR,CAM_CR,CHP_CR,CHH_CR,CMX_CR,COA_CR,COL_CR,DUR_CR,GUA_CR,GRO_CR,HID_CR,JAL_CR,MIC_CR,MOR_CR,MEX_CR,NAY_CR,NLE_CR,OAX_CR,PUE_CR,QUE_CR,ROO_CR,SLP_CR,SIN_CR,SON_CR,TAB_CR,TAM_CR,TLA_CR,VER_CR,YUC_CR,ZAC_CR,Conj_recovered
2020-03-13,0,0,0,0,1,0,2,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,6
2020-03-14,0,0,0,0,1,0,3,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,7
2020-03-15,0,0,0,0,1,0,3,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,9
2020-03-16,0,0,0,0,1,0,3,1,0,0,0,0,0,1,0,0,2,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,11
2020-03-17,0,0,0,0,1,0,3,1,0,0,0,0,0,1,0,0,2,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,11
2020-03-18,0,0,0,0,1,0,4,1,0,0,0,0,0,1,0,0,2,0,2,0,0,0,1,0,1,0,0,0,0,1,0,0,14
2020-03-19,0,0,0,0,1,0,4,1,0,0,0,0,0,2,0,0,3,0,2,0,2,1,1,0,1,0,0,0,0,1,0,0,19
2020-03-20,0,0,0,0,1,0,5,1,0,1,0,0,0,3,0,0,4,0,3,0,2,1,1,0,1,0,0,0,0,1,0,0,24
2020-03-21,0,0,0,0,1,0,10,1,0,1,0,0,1,4,0,0,6,0,5,0,2,1,1,1,1,0,0,0,0,1,1,0,37
2020-03-22,0,0,0,0,1,0,16,1,0,1,0,0,2,7,0,0,7,0,5,0,3,2,2,1,1,0,0,0,0,1,3,1,54
2020-03-23,0,1,0,1,1,0,22,1,0,2,0,1,2,9,1,0,9,0,12,1,7,3,3,2,2,0,1,0,0,1,4,1,87
2020-03-24,1,1,0,1,1,0,31,1,0,2,1,2,2,13,1,0,11,0,15,2,9,7,3,2,2,0,2,0,0,1,8,1,120
```
La última columna es el acumulado en el país. Además de que no considero defunciones (como lo hago, aunque un paciente haya fallecido, si pasaron más de 14 días del inicio de sus síntomas lo considero como "recuperado" ya que no tengo filtros para determinar los pacientes fallecidos a partir de hoy.), el total no concuerda con lo que reporta la SSa. Según la conferencia de hoy, el número de pacientes recuperados es como del 1-2% del total (i.e. 4-8, no 120).

Realmente este análisis no checa con el "gut feeling". Realmente, fuera de capturar los porcentajes de las conferencias u obtener un listado más detallado de la SSa, no veo cómo reportar adecuadamente casos que en verdad estén recuperados.

**Comment by jRicciL** [comment]
Concuerdo, creo que sería muy especulativo proceder así. Me parece recordar que en una de las conferencias el subsecretario comentó que los casos recuperados se confirmaban al realizar nuevamente la prueba por PCR en los pacientes infectados (buscaré el dato). Quizá en adelante no sean prioritarias esas pruebas (y su reporte no sea diario) para escatimar en ellas en favor de los nuevos casos. Difícil saberlo. Habrá que esperar a ver si vuelven a actualizar la cifra, o si seguirán manejando porcentajes.
De cualquier forma, de verdad, muchas gracias por tu trabajo! Y agradezco también tu referencia a la app con las gráficas! Más tarde adaptaré la app para reportar que no se cuentan con datos de recuperación para los días en los que la cifra aparezca en cero (a partir de ayer).

Si estás de acuerdo, y no hace falta algo más, podemos cerrar el issue.

Saludos,
Joel

**Comment by deathwebo** [comment]
Hola, justo me encontré con el problema de los recuperados y también me topé que el dato de los difuntos tampoco es proporcionado por gobierno. Me imagino a partir del 23 de Marzo ya solo se puede obtener los datos generales de los confirmados, recuperados y fallecidos pero esta información a nivel estado ya no será proporcionada cierto ?

Gracias!

**Comment by carranco-sga** [comment]
@jRicciL Sí, la SSa sí ha mencionado (y en los CTD dice) que los casos recuperados dan negativo a una segunda prueba, pero también mencionan (en las conferencias) que los casos activos sólo duran 14 días. Creo, en vista de no tener alternativa, no desglosar los recuperados. Una alternativa para no asumir que no hay recuperados, sería que en las tablas dejara en blanco el espacio respectivo. A lo mejor así es un poco menos confuso. ¿Qué opinas?

**Comment by carranco-sga** [comment]
@deathwebo Todavía se pueden obtener los confirmados y difuntos por estado (los primeros, incluyendo recuperados y fallecidos pero sin precisar quiénes) se pueden obtener de las tablas de casos diarios que publica la SSa (en el repo, están [archivadas aquí](https://github.com/carranco-sga/Mexico-COVID-19/tree/master/Documents/Tablas%20casos).)  Los fallecidos por estado se listan (hasta hoy, en el comunicado técnico diario [archivado aquí](https://github.com/carranco-sga/Mexico-COVID-19/tree/master/Documents/CTD).) Por desgracia los pacientes recuperados ya no se desglosan, hasta dónde sé, en ningún documento oficial. Es por esto que creo que salvo se libere la información de alguna forma, sólo podré actualizar la lista de casos confirmados y casos fallecidos por estado. 

Saludos, 
Gabriel.

**Comment by jRicciL** [comment]
Hola Gabriel, me parece mejor la idea que comentas de omitir el dato, ya sea dejando en blanco la casilla o con algún otro criterio de llenado ('NA' o 'NAN'), creo que cualquier caso es buena opción. Esperemos que el resto de los datos sigan siendo reportados de forma integra.

Saludos!
Joel.

**Comment by carranco-sga** [comment]
Hola a ambos,

He actualizado la tabla resumen para reflejar que no conocemos la información del número de recuperados por estado. Ahora dejo en blanco el espacio. (Y creo que es prudente cerrar el issue)

Saludos,
Gabriel.
