### ISSUE TITLE
Consulta muertes

### ISSUE THREAD

**Issue by bluepill5** [carranco-sga/Mexico-COVID-19#6]
**Saludos:**

Disculpa los datos de muertes se obtienen del Comunicado Técnico diario??? o hay otra fuente??? la pregunta es por que ahí solo veo las muertes por estados pero quería desglosarlo por edad y género, vi un artículo que lo hace pero no indica fuentes. De antemano gracias.

**Buen día.**

**Comment by carranco-sga** [comment]
Buenos días,

Las muestres se extraen de la tabla en el comunicado técnico diario. Sólo se listan por estado.

Saludos,
Gabriel Carranco
