### ISSUE TITLE
Comparto una visualización en Observable

### ISSUE THREAD

**Issue by hugomosh** [carranco-sga/Mexico-COVID-19#8]
Hola @carranco-sga,
Gracias por el gran esfuerzo de poner estos datos disponibles. Lo mismo a los demás colaboradores de datos y paneles. 

Hice una gráfica de carrera de barras a manera de homenaje. Quería compartirla. 
https://observablehq.com/@hugomosh/progreso-covid-19-mexico

**Comment by carranco-sga** [comment]
Muchas gracias, @hugomosh. Incluyo un link en el repositorio. 

Saludos,
Gabriel.
