### ISSUE TITLE
Pequeña discrepancia en número de sospechosos para 2020-04-03

### ISSUE THREAD

**Issue by mariorz** [carranco-sga/Mexico-COVID-19#9]
Hola, esta me parece la colección de datos más completa de Covid19 en México, muchas gracias por tu trabajo.

Yo he estado descargando los datos de este [mapa](https://ncov.sinave.gob.mx/mapa.aspx) a diario desde 2020-04-02 [en este repo](https://github.com/mariorz/covid19-mx-time-series). Esos datos coinciden completamente con los de tu [tabla](https://github.com/carranco-sga/Mexico-COVID-19/blob/master/Mexico_COVID19.csv) en cuanto a Muertes y Confirmados. En cuanto a Sospechosos, la única discrepancia es en 2020-04-03, donde para Jalisco,Veracruz. [Yo tengo](https://github.com/mariorz/covid19-mx-time-series/blob/master/data/covid19_suspects_mx.csv): 686, 403. Tu tienes: 687, 404. Después de ese dia los números en esos estados vuelven a coincidir. 

Supongo que para las muertes estamos usando el mismo mapa para obtener datos, ya que creo es la única fuente existente que segrega por estado. Para sospechosos y positivos, si tu estás usando los reportes técnicos diarios, pudiera ser que la discrepancia exista entre el reporte de ese día y el mapa de ese día. No se tu tengas otra intuición al respecto. Gracias!

**Comment by carranco-sga** [comment]
Hola, @mariorz. Gracias por tu comentario.

Permíteme darle una revisada a las tablas de ese día para ver si se trata de un error mío o una discrepancia con los datos del mapa de la DGE.

Respecto a la fuente de las defunciones por estado, hay al menos una oficial diferente a la del mapa: el comunicado técnico diario que archivo [aquí](https://github.com/carranco-sga/Mexico-COVID-19/tree/master/Documents/CTD). (Los enlaces a los documentos oficiales están documentados allí mismo también). Por lo general en la segunda página de cada uno, además de un resumen del número de casos positivos, sospechosos y negativos en el país, hay una tabla que desglosa los fallecimientos por estado.

Estas tablas todavía las vacío a mano para hacer mis listas de fallecimientos. Espero pronto poder hacer algo similar a las otras tablas para automatizar el proceso.

Saludos, 
Gabriel.

**Comment by mariorz** [comment]
> Respecto a la fuente de las defunciones por estado, hay al menos una oficial diferente a la del mapa: el comunicado técnico diario que archivo aquí.

Buenísimo. Gracias por la aclaración, no había notado ese apartado del CTD.

**Comment by mariorz** [comment]
El resumen en el CDT de ese día tiene 5398 sospechosos, que son dos más de los que descargué del mapa ese día. Parece como un error en los datos del mapa.  https://github.com/carranco-sga/Mexico-COVID-19/blob/master/Documents/CTD/202004/20200403.pdf

Voy a cerrar el issue, pero aprovecho para preguntarte si hay alguna razón por la que no llevas la cuenta de casos negativos por estado, y si sabes de alguna funte para esos datos. Gracias!

**Comment by carranco-sga** [comment]
Revisando mis datos, igual, parece que es un error en los datos del mapa.
Respecto al número de casos negativos por estado, la única fuente de la cual estoy enterado es el mapa que estás compilando, No he visto ni encontrado ninguna fuente federal al respecto.

Saludos,
Gabriel.
